version: "3.8"

services:
  file_counter:
    build: .
    container_name: file_counter
    volumes:
      - ./input_files:/app/input_files
      - ./logs:/app/logs
    stdin_open: true
    tty: true
